// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schemas

import "encoding/json"
import "fmt"

type QuestionsSchemaJson struct {
	// Tasks corresponds to the JSON schema field "tasks".
	Tasks []QuestionsSchemaJsonTasksElem `json:"tasks" yaml:"tasks" mapstructure:"tasks"`
}

type QuestionsSchemaJsonTasksElem struct {
	// CorrectAnswer corresponds to the JSON schema field "correct_answer".
	CorrectAnswer string `json:"correct_answer" yaml:"correct_answer" mapstructure:"correct_answer"`

	// IncorrectAnswers corresponds to the JSON schema field "incorrect_answers".
	IncorrectAnswers interface{} `json:"incorrect_answers" yaml:"incorrect_answers" mapstructure:"incorrect_answers"`

	// Question corresponds to the JSON schema field "question".
	Question string `json:"question" yaml:"question" mapstructure:"question"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *QuestionsSchemaJsonTasksElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["correct_answer"]; raw != nil && !ok {
		return fmt.Errorf("field correct_answer in QuestionsSchemaJsonTasksElem: required")
	}
	if _, ok := raw["incorrect_answers"]; raw != nil && !ok {
		return fmt.Errorf("field incorrect_answers in QuestionsSchemaJsonTasksElem: required")
	}
	if _, ok := raw["question"]; raw != nil && !ok {
		return fmt.Errorf("field question in QuestionsSchemaJsonTasksElem: required")
	}
	type Plain QuestionsSchemaJsonTasksElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if len(plain.CorrectAnswer) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "correct_answer", 1)
	}
	if len(plain.Question) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "question", 1)
	}
	*j = QuestionsSchemaJsonTasksElem(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *QuestionsSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["tasks"]; raw != nil && !ok {
		return fmt.Errorf("field tasks in QuestionsSchemaJson: required")
	}
	type Plain QuestionsSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Tasks != nil && len(plain.Tasks) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "tasks", 1)
	}
	*j = QuestionsSchemaJson(plain)
	return nil
}
